# Generated by Django 5.1.6 on 2025-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_tip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
