# Generated by Django 5.1.6 on 2025-02-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_tip_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
