# Generated by Django 5.1.6 on 2025-02-08 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tip_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='tip',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='likes',
        ),
        migrations.AddField(
            model_name='tip',
            name='likes',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
