# Generated by Django 5.1.6 on 2025-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_alter_comment_options_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
