# Generated by Django 5.1.6 on 2025-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_alter_tip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='body',
            field=models.TextField(help_text='Ausführliche Erklärung deines Tipps', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='img',
            field=models.ImageField(help_text='Inhaltsstarkes Bild zu deinem Tipp', null=True, upload_to='uploads/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(help_text='Ein aussagekräftiger Titel', max_length=200, verbose_name='Titel'),
        ),
    ]
