# Generated by Django 5.1.6 on 2025-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_alter_tip_body_alter_tip_img_alter_tip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Kommentar zu dem Post von @{{ tip.user.username }}', verbose_name='Nachricht'),
        ),
    ]
