# Generated by Django 5.1.6 on 2025-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Kommentar schreiben (bitte keine Beleidigungen)', verbose_name='Nachricht'),
        ),
    ]
