# Generated by Django 5.1.6 on 2025-02-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': []},
        ),
    ]
