# Generated by Django 5.1.6 on 2025-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(help_text='z.B. Einkaufsliste für Treffen mit Freunden am 01.01.2025', max_length=100, verbose_name='Titel für die Einkaufsliste'),
        ),
    ]
