# Generated by Django 5.1.6 on 2025-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0002_alter_shoppinglist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
