# Generated by Django 5.1.6 on 2025-02-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0003_alter_bulletpoint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
