# Generated by Django 5.1.6 on 2025-02-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0004_alter_bulletpoint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='text',
            field=models.CharField(help_text='z.B. Banane, Ananas, Apfel etc.', max_length=100, verbose_name='Titel für die Notiz'),
        ),
    ]
